### PR TITLE
Update useReducer 4th extra credit code

### PR DESCRIPTION
**Pull request by marbiano**
This PR makes a tiny update to the code, removing a line that is not needed.

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
That's intentional. It's because the place where you're supposed to copy/paste that code expects there to be a `count` variable.

Thanks anyway!

**Comment by marbiano** [comment]
@kentcdodds I understand that is needed below for render purposes, but in the context of that tiny bit of code, which is fully related to the update of reducer's API, it looks a bit out of place:

Screen Shot 2021-07-19 at 2 09 34 PM

But it's a super picky comment so happy to accept the closed PR too. :)

**Comment by kentcdodds** [comment]
The goal of these little snippets is to iteratively change the way you're using the reducer without changing any of the other code to illustrate that they're just different ways to solve the same problem and can be used in very similar ways. Reducing the amount of refactoring you need to do on unrelated parts is part of the point. Up to this exercise, we always had a `count` variable in scope and I'd like to keep it that way. Thanks!

**Comment by marbiano** [comment]
Thanks for the explanation, Kent!

**Pull request closed without merging**
